# Generated by Django 4.1.1 on 2022-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=76)),
                ('publishdate_book', models.DateField()),
                ('isbn_book', models.CharField(max_length=76)),
            ],
        ),
    ]
